// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zupkfonpfgmvkctwxqic.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp1cGtmb25wZmdtdmtjdHd4cWljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4NDkzNjYsImV4cCI6MjA2MzQyNTM2Nn0.5bDDskjJuHhZB-W7_f1L1PqSdmlWsWu2Un6nEweKjZQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);